--- 
after_success: 
  - "coverage report"
  - coveralls
branches: 
  only: 
    - master
dist: xenial
install: 
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install pytest"
  - "pip install flake8"
  - "pip install -r requirements.txt"
language: python
python: 
  - 3.7
script: 
  - "coverage run -m unittest discover"
  - "flake8 cmdbox"
sudo: true

